name: Github Actions 실행하기

on:
  push:
    branches:
      - main

jobs:
  My-first-CICD-job:
    runs-on: ubuntu-latest

    steps:
      - name: simple-web
        run: |
          ls -al
          pwd

      - name: simple-web2
        run: |
          echo "This is the second CI/CD step" >> a.txt

      - name: simple-web3
        run: |
          ls -al
          cat a.txt
