name: Github Actions 실행하기

on:
  push:
    branches:
      - main

jobs:
  My-first-CICD-job:
    runs-on: ubuntu-latest

    steps:
      - name: files-check
        run: |
          ls -al
          pwd

      - name: file-create
        run: |
          echo "This is the second CI/CD step" >> a.txt

      - name: simple-web3
        run: |
          ls -al
          cat a.txt

  github-variables-check-job:
    runs-on: ubuntu-latest

    steps:
      - name: multiple-lines
        run: |
          echo "line 1"
          echo "line 2"

      - name: github-variables-check
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
